# -*- coding: utf-8 -*-
# store all shortcut keys
menu = {"d": "database", "s": "session", "t": "Table", "m": "Memory", "D": "dynamicsql", "U": "lock",
        "W": "wait_event", "r": "replication"}
function_menu = {
    "home": {"p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "database": {"p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh", "F": "freeze screen",
                 "esc": "reset"},
    "session": {"a": "session_detail", "/": "conditional filtration", "z": "sort by column by", "f": "kill session",
                "left": "page left", "right": "page right", "p": "snapshoot(f9 save f10 discard)",
                "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "session_detail": {"f": "force", "e": "sql_explain", "p": "snapshoot(f9 save f10 discard)",
                       "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "sql_explain": {"b": "back to session_detail", "p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh",
                    "F": "freeze screen", "esc": "reset"},
    "table": {"a": "table_index", "/": "conditional filtration", "z": "sort by column",
              "left": "page left", "right": "page right", "h": "help", "q": "close",
              "p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh", "F": "freeze screen",
              "esc": "reset"},
    "table_index": {"p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh", "F": "freeze screen",
                    "esc": "reset"},
    "memory": {"S": "sharemem", "R": "top_mem_used_session", "p": "snapshoot(f9 save f10 discard)",
               "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "sharemem": {"/": "conditional filtration", "z": "sort by column", "p": "snapshoot(f9 save f10 discard)",
                 "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "top_mem_used_session": {"a": "session_detail", "/": "conditional filtration", "z": "sort by column",
                             "p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh", "F": "freeze screen",
                             "esc": "reset"},
    "dynamicsql": {"a": "view query detail", "p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh",
                   "F": "freeze screen", "esc": "reset"},
    "lock": {"L": "lock_chain", "a": "session_detail", "/": "conditional filtration",
             "z": "sort by column", "left": "page left ", "right": "page right", "p": "snapshoot(f9 save f10 discard)",
             "space": "immediate refresh", "F": "freeze screen",
             "esc": "reset"},
    "lock_chain": {"a": "session_detail", "/": "conditional filtration",
                   "z": "exted sort by column by selection point", "p": "snapshoot(f9 save f10 discard)",
                   "space": "immediate refresh", "F": "freeze screen",
                   "esc": "reset"},
    "wait_event": {"/": "conditional filtration", "z": "sort by column",
                   "j": "session sort by wait_event or wait_status", "p": "snapshoot(f9 save f10 discard)",
                   "space": "immediate refresh", "F": "freeze screen", "esc": "reset"},
    "replication": {"/": "conditional filtration", "left": "page left", "right": "page right",
                    "p": "snapshoot(f9 save f10 discard)", "space": "immediate refresh",
                    "F": "freeze screen", "esc": "reset"}
}

# page_field
sort_querys_dict = {
    "database": ["active session/session", "blks_hit/(blks_hit+read)", "select_count/dml_count", "DATA_IO_TIME/DB_TIME",
                 "dynamic_used_memory/max_dynamic_memory", "start_date", "start_time", "wal_status", "LocalRole",
                 "ProcesMem", "Dynamic_Mem", "Shared_Mem", "Session", "Actsess", "Waiting", "idleintran", "xact_commit",
                 "xact_rollback", "totalcount", "ddl_count", "dml_count", "dcl_count", "select_count", "update_count",
                 "insert_count", "delete_count", "num_cpus", "num_cpu_cores", "num_cpu_sockets", "blks_read",
                 "blks_hit", "hitratio", "tup_fetched", "tup_inserted", "tup_update", "tup_delete", "DB_TIME",
                 "cpu_time", "execute_time", "data_io_time", "blk_read_time", "blk_write_time", "redo_writetim",
                 "temp_files", "temp_bytes", "conflicts", "deadlocks", "checkpoints", "pgwrits", "double_writes",
                 "physical_memory_bytes", "idle_time", "busy_time", "user_time", "sys_time", "iowait_time", "nice_time",
                 "vm_page_in_bytes", "vm_page_out_bytes", "os_load_processes"],
    "session": ["active session/session", "n_commit", "n_blocks_fetched", "n_rollback", "n_local_blocks_read",
                "n_physical_read_operation", "n_sql", "n_sort_in_disk", "n_shared_blocks_dirtied", "n_table_scan",
                "n_cu_hdd_asyn_read", "n_local_blocks_dirtied", "n_shared_blocks_read", "n_blocks_read_time",
                "n_blocks_write_time", "n_sort_in_memory", "n_cu_mem_hit", "n_cu_hdd_sync_read", "pid", "current_state",
                "db_name", "user_name", "application_name", "client_addr", "xact_start_time", "state_change_time",
                "waiting", "wait_status", "wait_event", "db_time", "cpu_time", "execute_time", "data_io_time", "query"],
    "session_detail": ["query_id", "state_sum", "backend_start", "query_start", "datid", "datname", "usesysid",
                       "usename", "application_name", "client_addr", "client_hostname", "client_port",
                       "xact_start_time", "state_change_time", "waiting", "total_cpu_time", "db_time", "cpu_time",
                       "execute_time", "data_io_time", "parse_time", "plan_time", "rewrite_time", "net_send_time",
                       "init_mem", "used_mem", "peak_mem", "wait_status", "locktag", "lockmode",
                       "block_sessionid", "pl_execuyion_time", "pl_compilation_time", "query"],
    "session_plan": ["advise", "explain"],
    "table": ["relname", "schemaname", "datname", "idx_blks_hit", "idx_blks_read", "toast_blks_read",
              "toast_blks_hit", "tidx_blks_read", "tidx_blks_hit", "tabsize", "idxsize", "totalsize", "n_live_tup",
              "n_dead_tup", "seq_scan", "seq_tup_read", "idx_scan", "idx_tup_fetch", "n_tup_ins", "n_tup_upd",
              "n_tup_del", "n_tup_hot_upd", "heap_blks_read", "heap_blks_hit", "phywrts", "phyblkrd", "phyblkwrt",
              "readtim", "writetim", "snaptime", "last_vacuum", "last_autovacuum", "last_analyze", "last_autoanalyze",
              "last_data_changed"],
    "table_index": ["indexrelname", "relname", "schemaname", "datname", "idx_scan", "idx_tup_read", "idx_tup_fetch",
                    "idx_blks_hit", "phyrds", "phywrts", "phyblkrd", "phyblkwrt", "readtim", "writetim"],
    "lock": ["data_length", "pid", "locktype", "database", "relname", "page", "tuple", "transactionid", "virtualxid",
             "objid", "virtualtransaction", "mode", "granted", "fastpath", "locktag"],
    "lock_detail": ["blocker_holder", "lock_blocked_agent_id"],
    "wait_event": ["data_length", "nodename", "type", "event", "wait", "failed_wait", "total_wait_time",
                   "avg_wait_time", "history_max_wait_time", "history_min_wait_time", "last_updated"],
    "memory": ["process_memory_used_percent", "dynamic_memory_used_percent", "backend_memory_used_percent",
               "shared_memory_used_percent", "cstore_memory_used_percent", "sctpcomm_memory_used_percent",
               "gpu_dynamic_memory_used_percent", "target_ip", "max_process_memory", "process_used_memory", "max_dynamic_memory",
               "dynamic_used_memory", "dynamic_used_shrctx", "max_backend_memory", "backend_used_memory",
               "max_shared_memory", "shared_used_memory", "max_cstore_memory", "cstore_used_memory",
               "max_sctpcomm_memory", "sctpcomm_used_memory", "other_used_memory", "gpu_max_dynamic_memory",
               "gpu_dynamic_used_memory", "pooler_conn_memory", "pooler_freeconn_memory", "storage_compress_memory",
               "udf_reserved_memory"],
    'sharemem': ["data_length", "parent", "contextname", "level", "totalsize", "freesize", "usedsize",
                 "usedsize/totalsize"],
    "top_mem_used_session": ["data_length", "pid", "init_mem", "used_mem", "peak_mem", "query", "usename",
                             "client_addr"],
    "dynamicsql": ["data_length", "query", "n_calls", "avg_db_time", "user_name", "db_time", "cpu_time",
                   "execution_time", "parse_time", "plan_time", "total_elapse_time", "n_returned_rows", "data_io_time",
                   "n_tuples_fetched", "n_tuples_returned", "n_tuples_inserted", "n_tuples_updated", "n_tuples_deleted",
                   "n_blocks_fetched", "n_blocks_hit", "n_soft_parse", "n_hard_parse", "rewrite_time",
                   "pl_execution_time", "pl_compilation_time", "net_send_info", "net_recv_info", "net_stream_send_info",
                   "net_stream_recv_info", "sort_count", "sort_time", "sort_mem_used", "sort_spill_count",
                   "sort_spill_size", "hash_count", "hash_time", "hash_mem_used", "hash_spill_count", "hash_spill_size",
                   "unique_sql_id"],
    "replication": ["local_role", "peer_role", "peer_state", "sync_percent", "sync_state", "sender_sent_location",
                    "sender_write_location", "sender_flush_location", "sender_replay_location",
                    "receiver_received_location", "receiver_write_location", "receiver_flush_location",
                    "receiver_replay_location", "receive_gap", "replay_gap"]
}
